export enum ButtonNames {
    backspace = "delete",
    equals = "equals",
    escape = "clear",
    zero = "0",
    one = "1",
    two = "2",
    three = "3",
    four = "4",
    five = "5",
    six = "6",
    seven = "7",
    eight = "8",
    nine = "9",
    multiply = "multiply",
    plus = "plus",
    minus = "minus",
    separator = "separator",
    divide = "divide",
    percent = "percent",
    plus_minus = "plus-minus"
}